version: '3'

services:
  database:
    ports:
      - "27017:27017"
    volumes:
      - /data/db

  maestro:
    ports:
      - '8182:8182'
    environment:
      MAESTRO_LOGGING_LEVEL: debug

  frontend:
    ports:
      - '3000:3000'
    environment:
      PUBLIC_API_URL: http://localhost:8182
