version: "3.9"
services:
  database:
    restart: always
    image: 'mongo:5.0.5'
    ports:
      - "27017:27017"
    env_file:
      - ../configs/.env
    volumes:
      - ../configs/mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro
      - mongo-data:/data/db

  maestro:
    build:
      context: ../
      dockerfile: build/package/maestro/Dockerfile
    ports:
      - '8080:8080'
    environment:
      MAESTRO_API_PORT: 8080
      MAESTRO_DATABASE_HOST: database
      MAESTRO_DATABASE_PORT: 27017
    env_file:
      - ../configs/.env
    depends_on:
      - database

  frontend:
    build:
      context: ../web/frontend-remix/
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      API_URL: http://maestro:8080
    depends_on:
      - maestro

volumes:
  mongo-data:
  prometheus-data:
  grafana-data: