version: '3'

services:
  maestro:
    ports:
      - '8182'
    environment:
      MAESTRO_LOGGING_LEVEL: info
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`${HOST}`) && PathPrefix(`/api`)"
      - "traefik.http.middlewares.strip-prefix.stripprefix.prefixes=/api"
      - "traefik.http.middlewares.strip-prefix.stripprefix.forceslash=false"
      - "traefik.http.routers.api.middlewares=strip-prefix@docker"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.port=8182"

  frontend:
    ports:
      - '3000'
    environment:
      PUBLIC_API_URL: http://${HOST}/api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${HOST}`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.port=3000"

  traefik:
    image: traefik:v2.5
    command: --api.insecure=true --providers.docker --providers.docker.exposedbydefault=false --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8080:8080"
    depends_on:
      - maestro
      - frontend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
