version: "3.9"
services:
  database:
    image: 'bitnami/mongodb:5.0.8'
    environment:

      # Root user
      MONGODB_ROOT_USER: ${MONGO_INITDB_ROOT_USERNAME}
      MONGODB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

      # Maestro user
      MONGODB_USERNAME: ${MONGO_MAESTRO_USERNAME}
      MONGODB_PASSWORD: ${MONGO_MAESTRO_PASSWORD}
      MONGODB_DATABASE: ${MONGO_MAESTRO_DATABASE}

      # ReplicaSet stuff
      MONGODB_ADVERTISED_HOSTNAME: database
      MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: rs0key
    ports:
      - "27017:27017"
    volumes:
      # - mongo-data:/data/db # (Optional) Use this if you want the data to persist between runs
      - /data/db

  maestro:
    build:
      context: ../
      dockerfile: build/package/maestro/Dockerfile
    environment:
      MAESTRO_API_PORT: 8182
      MAESTRO_LOGGING_LEVEL: debug

      # Database
      MAESTRO_DATABASE_URI: ${MAESTRO_DATABASE_URI}
      MAESTRO_DATABASE_NAME: ${MAESTRO_DATABASE_NAME}

      # Services
      MAESTRO_SERVICES_APPLE_MUSIC_TOKEN: ${MAESTRO_SERVICES_APPLE_MUSIC_TOKEN}
      MAESTRO_SERVICES_SPOTIFY_CLIENT_ID: ${MAESTRO_SERVICES_SPOTIFY_CLIENT_ID}
      MAESTRO_SERVICES_SPOTIFY_CLIENT_SECRET: ${MAESTRO_SERVICES_SPOTIFY_CLIENT_SECRET}
    ports:
      - "8182:8182"
    volumes:
      - ../configs/maestro.yaml:/maestro.yaml
    depends_on:
      - database

  frontend:
    build:
      context: ../web/frontend-remix/
      dockerfile: Dockerfile
    environment:
      API_URL: http://maestro:8182
      PUBLIC_API_URL: http://localhost:8182
    ports:
      - "3000:3000"
    depends_on:
      - maestro
