version: "3.9"
services:
  database:
    restart: always
    image: 'mongo:5.0.5'
    ports:
      - "27017:27017"
    env_file:
      - ../configs/mongo/.env
    volumes:
      - ../configs/mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro
      # - mongo-data:/data/db

  maestro:
    build:
      context: ../
      dockerfile: build/package/maestro/Dockerfile
    ports:
      - '8080:8080'
    environment:
      MAESTRO_API_PORT: 8080
      MAESTRO_DATABASE_HOST: database
      MAESTRO_DATABASE_PORT: 27017
      MAESTRO_DATABASE_USER: maestro
      MAESTRO_DATABASE_PASSWORD: maestro
      MAESTRO_DATABASE_DATABASE: maestro
    env_file:
      - ../configs/.env
    depends_on:
      - database

  frontend:
    build:
      context: ../web/frontend-remix/
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      API_URL: http://maestro:8080
    depends_on:
      - maestro

  # Monitoring
  prometheus:
    image: prom/prometheus:v2.32.1
    ports:
      - '9000:9090'
    volumes:
      - ../configs/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - maestro

  grafana:
    image: grafana/grafana:8.3.3
    ports:
      - "3010:3010"
    volumes:
      - ../configs/grafana:/etc/grafana
      # - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  mongo-data:
  prometheus-data: