version: "3.9"
services:
  database:
    image: ghcr.io/zcube/bitnami-compat/mongodb:6.0.4
    environment:

      # Root user
      MONGODB_ROOT_USER: ${MONGO_INITDB_ROOT_USERNAME:?error}
      MONGODB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:?error}

      # Maestro user
      MONGODB_USERNAME: ${MONGO_MAESTRO_USERNAME:?error}
      MONGODB_PASSWORD: ${MONGO_MAESTRO_PASSWORD:?error}
      MONGODB_DATABASE: ${MONGO_MAESTRO_DATABASE:?error}

      # ReplicaSet stuff (Required for transactions apparently...)
      MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: rs0key

      # Use this when connecting from outside of docker-compose
      # MONGODB_ADVERTISED_HOSTNAME: localhost

    ports:
      - "27017:27017"

    volumes:
      # - mongo-data:/data/db # (Optional) Use this if you want the data to persist between runs
      - /data/db

  maestro:
    build:
      dockerfile: Dockerfile

    environment:

      # Frontend
      PUBLIC_API_URL: http://localhost:4000/api

      # API
      # Logging
      MAESTRO_LOGGING_LEVEL: debug

      # Database
      MAESTRO_DATABASE_URI: mongodb://${MONGO_MAESTRO_USERNAME:?error}:${MONGO_MAESTRO_PASSWORD:?error}@database:27017/${MONGO_MAESTRO_DATABASE:?error}?authSource=${MONGO_MAESTRO_DATABASE:?error}&replicaSet=rs0
      MAESTRO_DATABASE_NAME: ${MONGO_MAESTRO_DATABASE:?error}

      # Services
      MAESTRO_SERVICES_APPLE_MUSIC_TOKEN: ${MAESTRO_SERVICES_APPLE_MUSIC_TOKEN:?error}
      MAESTRO_SERVICES_SPOTIFY_CLIENT_ID: ${MAESTRO_SERVICES_SPOTIFY_CLIENT_ID:?error}
      MAESTRO_SERVICES_SPOTIFY_CLIENT_SECRET: ${MAESTRO_SERVICES_SPOTIFY_CLIENT_SECRET:?error}

    ports:
      - "8182:8182" # Backend
      - "4000:4000" # Frontend

    volumes:
      - ./configs/maestro.yaml:/etc/maestro/maestro.yaml

    depends_on:
      - database
