version: "3.9"
services:
  database:
    image: ghcr.io/zcube/bitnami-compat/mongodb:6.0.4
    environment:

      # Root user
      MONGODB_ROOT_USER: ${MONGO_INITDB_ROOT_USERNAME}
      MONGODB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

      # Maestro user
      MONGODB_USERNAME: ${MONGO_MAESTRO_USERNAME}
      MONGODB_PASSWORD: ${MONGO_MAESTRO_PASSWORD}
      MONGODB_DATABASE: ${MONGO_MAESTRO_DATABASE}

      # ReplicaSet stuff
      # Use this when accessing from docker compose or k8s
      MONGODB_ADVERTISED_HOSTNAME: database

      # Use this when accessing from outside of docker compose or k8s
      # MONGODB_ADVERTISED_HOSTNAME: localhost

      MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: rs0key

    ports:
      - "27017:27017"

    volumes:
      # - mongo-data:/data/db # (Optional) Use this if you want the data to persist between runs
      - /data/db

  maestro:
    build:
      dockerfile: Dockerfile

    environment:
      # Frontend
      PUBLIC_API_URL: http://localhost:8182

      # API
      MAESTRO_API_PORT: 8182
      MAESTRO_LOGGING_LEVEL: debug

      # Database
      MAESTRO_DATABASE_URI: mongodb://${MONGO_MAESTRO_USERNAME}:${MONGO_MAESTRO_PASSWORD}@database:27017/${MONGO_MAESTRO_DATABASE}?authSource=${MONGO_MAESTRO_DATABASE}&replicaSet=rs0
      MAESTRO_DATABASE_NAME: ${MONGO_MAESTRO_DATABASE}

      # Services
      MAESTRO_SERVICES_APPLE_MUSIC_TOKEN: ${MAESTRO_SERVICES_APPLE_MUSIC_TOKEN}
      MAESTRO_SERVICES_SPOTIFY_CLIENT_ID: ${MAESTRO_SERVICES_SPOTIFY_CLIENT_ID}
      MAESTRO_SERVICES_SPOTIFY_CLIENT_SECRET: ${MAESTRO_SERVICES_SPOTIFY_CLIENT_SECRET}

    ports:
      - "8182:8182" # Backend
      - "3000:3000" # Frontend

    volumes:
      - ./configs/maestro.yaml:/etc/maestro/maestro.yaml

    depends_on:
      - database
