---

apiVersion: v1
kind: ConfigMap
metadata:
  name: host-config
data:
#  # Unused
#  host: maestro.yukitsune.dev
#  traefik-host: Host(`maestro.yukitsune.dev`)
#  traefik-host-api: Host(`maestro.yukitsune.dev`) && PathPrefix(`/api`)

  https-host: https://maestro.yukitsune.dev