---

apiVersion: v1
kind: ConfigMap
metadata:
  name: maestro-api-config
data:
  maestro.yaml: |
    api:
      port: 8182
    logging:
      level: info
    services:
      apple_music:
        name: "Apple Music"
        logo_file_name: "apple_music.png"
        enabled: true
      deezer:
        name: "Deezer"
        logo_file_name: "deezer.png"
        enabled: true
      spotify:
        name: "Spotify"
        logo_file_name: "spotify.png"
        enabled: true