{
 "title": "Maestro API",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Requests (5m)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(maestro_request_count[5m])"
    }
   ]
  },
  {
   "title": "Database Calls (5m)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(maestro_db_call_count[5m])"
    }
   ]
  },
  {
   "title": "Requests (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Reqs" } },
   "targets": [
    {
     "expr": "increase(maestro_request_count[5m])"
    }
   ]
  },
  {
   "title": "Average Request Duration (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(maestro_request_duration_sum[5m]) / rate(maestro_request_duration_count[5m])"
    }
   ]
  },
  {
   "title": "Database Calls (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "increase(maestro_db_call_count[5m])"
    }
   ]
  },
  {
   "title": "Server Errors (5m)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(maestro_server_error_count[5m])"
    }
   ]
  },
  {
   "title": "Client Errors (5m)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(maestro_client_error_count[5m])"
    }
   ]
  },
  {
   "title": "API Requests (24h)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "increase(maestro_spotify_request_count[24h])",
     "legendFormat": "Spotify"
    },
    {
     "expr": "increase(maestro_apple_music_request_count[24h])",
     "legendFormat": "Apple Music"
    },
    {
     "expr": "increase(maestro_deezer_request_count[24h])",
     "legendFormat": "Deezer"
    }
   ]
  }
 ]
}