apiVersion: v1
kind: Secret
metadata:
  name: maestro-secret
type: Opaque
stringData:

  # Database
  database-uri:
  database-name: maestro

  # Services
  apple-music-token:
  spotify-id:
  spotify-secret:

---

# (Optional) CA Certificate for MongoDB
apiVersion: v1
kind: Secret
metadata:
  name: maestro-secret-mongo-tls
type: kubernetes.io/tls
data:
  mongo-tls.crt: |