apiVersion: v1
kind: Secret
metadata:
  name: maestro-secret
type: Opaque
stringData:

  # Database
  database-host:
  database-username:
  database-password:

  # Services
  apple-music-token:
  spotify-id:
  spotify-secret:
