---

apiVersion: v1
kind: Secret
metadata:
  name: maestro-secret
type: Opaque
stringData:

  # Database
  database-uri: {{ required "database.mongoUri is required" .Values.database.mongoUri }}
  database-name: {{ required "database.mongoDatabaseName is required" .Values.database.mongoDatabaseName }}

  # Services
  apple-music-token: {{ required "services.appleMusic.token is required" .Values.services.appleMusic.token }}
  spotify-id: {{ required "services.spotify.clientId is required" .Values.services.spotify.clientId }}
  spotify-secret: {{ required "services.spotify.clientSecret is required" .Values.services.spotify.clientSecret }}

---

apiVersion: v1
kind: Secret
metadata:
  name: maestro-secret-mongo-tls
type: Opaque
data:
  tls.crt: {{ .Values.database.mongoTlsCert | b64enc }}
