api:
  assets_dir: ./assets
  port: 8182
logging:
  level: debug
services:
  apple_music:
    name: "Apple Music"
    logo_file_name: "apple_music.png"
    enabled: true
  deezer:
    name: "Deezer"
    logo_file_name: "deezer.png"
    enabled: true
  spotify:
    name: "Spotify"
    logo_file_name: "spotify.png"
    enabled: true
