api:
  port: 8182
database:
  host: localhost
  port: 27017
  user: maestro
  password: maestro
  database: maestro
services:
  apple_music:
    enabled: true
    token:
  deezer:
    enabled: true
  spotify:
    enabled: true
    client_id:
    client_secret:
