api:
  port: 8182
logging:
  level: debug
  use_json_format: false
database:
  host: localhost
  port: 27017
  user: maestro
  password: maestro
  database: maestro
services:
  apple_music:
    name: "Apple Music"
    artwork_link: "TODO"
    enabled: true
  deezer:
    name: "Deezer"
    artwork_link: "TODO"
    enabled: true
  spotify:
    name: "Spotify"
    artwork_link: "TODO"
    enabled: true
