api:
  port: 8182
database:
  host: localhost
  port: 27017
  user: maestro
  password: maestro
  database: maestro
services:
  - serviceName: AppleMusic
    enabled: true
    properties:
      token:
  - serviceName: Spotify
    enabled: true
    properties:
      clientId:
      clientSecret:
  - serviceName: Deezer
    enabled: true