api:
  port: 8182
database:
  host: localhost
  port: 27017
  user: maestro
  password: maestro
  database: maestro
services:
  apple_music:
    name: "Apple Music"
    artwork_link:
    enabled: true
    private_key_file:
    key_id:
    team_id:
  deezer:
    name: "Deezer"
    artwork_link:
    enabled: true
  spotify:
    name: "Spotify"
    artwork_link:
    enabled: true
    client_id:
    client_secret:
