api:
  assets_dir: ./assets
  port: 8182
logging:
  level: debug
database:
  host: localhost
  port: 27017
  user: maestro
  password: maestro
  database: maestro
services:
  apple_music:
    name: "Apple Music"
    logo_file_name: "apple_music.png"
    enabled: true
  deezer:
    name: "Deezer"
    artwork_link: "deezer.png"
    enabled: true
  spotify:
    name: "Spotify"
    artwork_link: "spotify.png"
    enabled: true
