---

# Maestro frontend deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maestro-frontend-deployment
spec:
  selector:
    matchLabels:
      app: maestro-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: maestro-frontend
    spec:

      containers:
        - name: maestro-frontend
          image: ghcr.io/yukitsune/maestro-frontend:v0.1.3
          ports:
            - containerPort: 3000
          env:
            - name: API_URL
              value: http://maestro-api-service

            - name: PUBLIC_API_URL
              value: {{ required "publicApiUrl is required" .Values.publicApiUrl }}

---

# Maestro frontend service
apiVersion: v1
kind: Service
metadata:
  name: maestro-frontend-service
spec:
  type: ClusterIP
  selector:
    app: maestro-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
