---

# Maestro API deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maestro-api-deployment
spec:
  selector:
    matchLabels:
      app: maestro-api
  replicas: 1
  template:
    metadata:
      labels:
        app: maestro-api
    spec:

      # Maestro config file
      volumes:
        - name: config
          configMap:
            name: maestro-api-config

        {{/* (Optional) MongoDB TLS Certificate */}}
        {{if .Values.database.mongoTlsCert}}
        - name: mongo-tls
          secret:
            secretName: maestro-secret-mongo-tls
        {{end}}

      containers:
        - name: maestro-api
          image: ghcr.io/yukitsune/maestro-api:v0.2.5
          ports:
            - containerPort: 8182
          volumeMounts:
            - name: config
              mountPath: "/etc/maestro"
              readOnly: true

            {{/* (Optional) MongoDB TLS Certificate */}}
            {{if .Values.database.mongoTlsCert}}
            - name: mongo-tls
              mountPath: "/etc/maestro/mongo"
              readOnly: true
            {{end}}
          env:

            # Database
            - name: MAESTRO_DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: maestro-secret
                  key: database-uri

            - name: MAESTRO_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: maestro-secret
                  key: database-name

            # Services
            - name: MAESTRO_SERVICES_APPLE_MUSIC_TOKEN
              valueFrom:
                secretKeyRef:
                  name: maestro-secret
                  key: apple-music-token

            - name: MAESTRO_SERVICES_SPOTIFY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: maestro-secret
                  key: spotify-id

            - name: MAESTRO_SERVICES_SPOTIFY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: maestro-secret
                  key: spotify-secret
          
          {{ with .Values.apiResources }}
            resources:
            {{ toYaml . | indent 14 }}
          {{ end }}

---

# Maestro API service
apiVersion: v1
kind: Service
metadata:
  name: maestro-api-service
spec:
  type: ClusterIP
  selector:
    app: maestro-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8182
