---

apiVersion: v1
kind: ConfigMap
metadata:
  name: maestro-api-config
data:
  maestro.yaml: |
    api:
      assets_dir: /assets
      port: 8182
    logging:
      level: {{ .Values.log.level }}
      loki:
        host: {{ .Values.log.loki.host }}
        labels:
          {{- range $key, $value := .Values.log.loki.labels }}
          {{ $key }}: {{ $value }}
          {{- end }}
    database:
      uri:
      name: maestro
    services:
      apple_music:
        name: "Apple Music"
        logo_file_name: "apple_music.png"
        enabled: true
        token:
      deezer:
        name: "Deezer"
        logo_file_name: "deezer.png"
        enabled: true
      spotify:
        name: "Spotify"
        logo_file_name: "spotify.png"
        enabled: true
        client_id:
        client_secret:
