name: Build and push Docker image.

on:
  release:
    types: [published]

jobs:

  build-api:
    name: Build and push the Docker image
    runs-on: ubuntu-latest
    
    env:
      IMAGE_NAME: ghcr.io/yukitsune/maestro:${{ github.event.release.tag_name }}

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build \
          --file Dockerfile \
          --tag ${{ env.IMAGE_NAME }} \
          --build-arg GIT_COMMIT="${{ github.sha }}" \
          --build-arg GIT_DIRTY="false" \
          --build-arg VERSION="${{ github.event.release.tag_name }}" \
          .

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1.12.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image
      run: docker push ${{ env.IMAGE_NAME }}
